let Info = [
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",
   "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe voluptatum iste nobis nostrum reprehenderit molestiae? Est totam ipsam reprehenderit nobis recusandae dignissimos reiciendis, facilis minima iusto animi neque porro obcaecati non iure voluptates impedit velit ullam dolore magni quos officia?",

]

export default Info;